MainDMMM/Models/Entities/ImageSlider.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MainDMMM.Models.Entities
{
    public class ImageSlider
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public string ContentType { get; set; }
        public byte[] Content { get; set; }
        [Display(Name = "Slider Alt")]
        public string SliderAlt { get; set; }
       
        [Display(Name = "Current Slider")]
        public bool CurrentSlider { get; set; }
    }
}

MainDMMM/Areas/AdminPanel/Controllers/ImageSlidersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MainDMMM.Models;
using MainDMMM.Models.Entities;
using MainDMMM.Areas.Data.IServices;
using MainDMMM.Areas.Data.Services;

namespace MainDMMM.Areas.AdminPanel.Controllers
{
    [Authorize(Roles = "Admin,SuperAdmin")]
    public class ImageSlidersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private IimageSliderServices _ImageSliderServices = new ImageSliderServices();

        public ImageSlidersController()
        { }
        public ImageSlidersController(ImageSliderServices imageServices)
        {
            _ImageSliderServices = imageServices;
        }

        // GET: Admin/ImageSliders
        public async Task<ActionResult> Index()
        {
            var imageSlider = await _ImageSliderServices.List();
            return View(imageSlider);
        }

        // GET: Admin/ImageSliders/Details/5
        //public async Task<ActionResult> Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }

        //    return View(imageSlider);
        //}

        // GET: Admin/ImageSliders/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/ImageSliders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ImageSlider models, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                models.CurrentSlider = true;
                await _ImageSliderServices.New(models, upload);
                return RedirectToAction("Index");
            }

            return View(models);
        }

        // GET: Admin/ImageSliders/Edit/5
        //public async Task<ActionResult> Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    var imageSlider = await _ImageSliderServices.
        //    return View(imageSlider);
        //}

        // POST: Admin/ImageSliders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<ActionResult> AddToSlider(int id)
        {
            var models = await db.ImageSlider.FindAsync(id);
            await _ImageSliderServices.AddToSlider(models);
            return RedirectToAction("Index");

        }

        // GET: Admin/ImageSliders/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ImageSlider imageSlider = await db.ImageSlider.FindAsync(id);
            if (imageSlider == null)
            {
                return HttpNotFound();
            }
            return View(imageSlider);
        }

        // POST: Admin/ImageSliders/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            await _ImageSliderServices.Delete(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MainDMMM/Areas/AdminPanel/Views/ImageSliders/Create.cshtml
@model MainDMMM.Models.Entities.ImageSlider

@{
    ViewBag.Title = "Create";
}


<div class="row">
    <!-- left column -->
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">New Slider</h3>
            </div>
            @using (Html.BeginForm("Create", "ImageSliders", null, FormMethod.Post, new { id = "", enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="box-body">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group">
                        @Html.Label("Name", htmlAttributes: new { @class = "control-label" })
                        <div class="">
                            @Html.EditorFor(model => model.FileName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.FileName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label>Slider Image</label>
                        <div class="">
                            <input type="file" name="upload" class="form-control" />
                        </div>
                    </div>



                    <div class="form-group">
                        @Html.LabelFor(model => model.SliderAlt, htmlAttributes: new { @class = "control-label" })
                        <div class="">
                            @Html.EditorFor(model => model.SliderAlt, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.SliderAlt, "", new { @class = "text-danger" })
                        </div>
                    </div>

                </div>

                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a href="javascript: history.back()" class="btn btn-default">Cancel</a>
                </div>

            }
        </div>

    </div>
    <div class="col-md-3"></div>

</div>

MainDMMM/Areas/AdminPanel/Views/ImageSliders/Delete.cshtml
@model MainDMMM.Models.Entities.ImageSlider

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ImageSlider</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FileName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContentType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContentType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SliderAlt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SliderAlt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CurrentSlider)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CurrentSlider)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MainDMMM/Areas/AdminPanel/Views/ImageSliders/Details.cshtml
@model MainDMMM.Models.Entities.ImageSlider

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ImageSlider</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FileName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContentType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContentType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SliderAlt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SliderAlt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CurrentSlider)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CurrentSlider)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MainDMMM/Areas/AdminPanel/Views/ImageSliders/Edit.cshtml
@model MainDMMM.Models.Entities.ImageSlider

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ImageSlider</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FileName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FileName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FileName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContentType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContentType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContentType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SliderAlt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SliderAlt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SliderAlt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CurrentSlider, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.CurrentSlider)
                    @Html.ValidationMessageFor(model => model.CurrentSlider, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MainDMMM/Areas/AdminPanel/Views/ImageSliders/Index.cshtml
@model IEnumerable<MainDMMM.Models.Entities.ImageSlider>

@{
    ViewBag.Title = "Index";
}



<div class="row">
    <div class="col-xs-12">
        <div class="box" style="padding:7px;">
            <div class="box-header" style="margin-bottom:15px;">
                <h3 class="box-title"><i class="fa fa-fw fa-file-text-o"></i> Slider Management</h3>

                <div class="box-tools">
                    @Html.ActionLink("New Slider", "Create", null, new { @class = "btn btn-primary", style = "padding: 7px;" })
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
                <table class="table table-hover">

                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayName("Name")
                            </th>
                            <th>
                                @Html.DisplayName("Image Alt")
                            </th>
                            <th>
                                @Html.DisplayName("Add To Slider")
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @if (item.Content != null)
                                    {
                                        <img src="data:image/jpg;base64,@(Convert.ToBase64String(item.Content))" class="img-responsive" style="width:150px;" />

                                    }
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.SliderAlt)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CurrentSlider)
                                </td>
                                <td>
                                    <div class="btn-group btn-group-xs">
                                        <button type="button" class="btn btn-default btn-flat">Action</button>
                                        <button type="button" class="btn btn-default btn-flat dropdown-toggle" data-toggle="dropdown">
                                            <span class="caret"></span>
                                            <span class="sr-only">Toggle Dropdown</span>
                                        </button>
                                        <ul class="dropdown-menu" role="menu">

                                            @* <li>@Html.ActionLink("Delete", "Delete", new { id = item.Id })</li>*@
                                            @if (item.CurrentSlider == false)
                                            {
                                                <li>@Html.ActionLink("Add to Slider", "AddToSlider", new { id = item.Id })</li>
                                            }
                                            else
                                            {
                                                <li>@Html.ActionLink("Remove from Slider", "AddToSlider", new { id = item.Id })</li>
                                            }
                                            <li>@Html.ActionLink("Delete Slider", "DeleteConfirmed", new { id = item.Id })</li>

                                        </ul>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>



                </table>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
</div>