MainDMMM/Controllers/PublicationsController.cs
using MainDMMM.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Data;
using PagedList;
using System.Net;
using MainDMMM.Models.Entities;

namespace MainDMMM.Controllers
{
    public class PublicationsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Publications
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult News(string searchString, string currentFilter, int? page)
        {

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            var items = db.Posts.Include(x => x.ImageModels).Include(d => d.Comments);

            if (!String.IsNullOrEmpty(searchString))
            {
                items = items.Where(p => p.Title.ToUpper().Contains(searchString.ToUpper())
                    || p.Content.ToUpper().Contains(searchString.ToUpper()));
                    
            }
            items = items.OrderBy(x => x.DatePosted);
            int pageSize = 6;
            int pageNumber = (page ?? 1);
            

            var calendar = db.Events.OrderBy(x => x.Start).Take(9).ToList();
            ViewBag.events = calendar;
            return View(items.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Preview(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var post = db.Posts.Include(x => x.ImageModels).Include(x=>x.Comments).FirstOrDefault(x => x.Id == id);
            var img = db.ImageModel.Where(x => x.PostId == id);
            var img1 = db.ImageModel.Where(x => x.PostId == id).FirstOrDefault().ImageContent;
            ViewBag.firstimage = img1;
            ViewBag.img = img;
           
            if (post == null)
            {
                return HttpNotFound();
            }

            var calendar = db.Events.OrderBy(x => x.Start).Take(9).ToList();
            ViewBag.events = calendar;
            return View(post);
        }

        public ActionResult Comment(int id, string text, string name, string Email)
        {
            var post = db.Posts.FirstOrDefault(x => x.Id == id);
            if(post != null)
            {
                Comment com = new Comment();
                com.Name = name;
                com.DateCommented = DateTime.UtcNow.AddHours(1);
                com.Email = Email;
                com.Content = text;
                com.PostId = id;
                db.Comments.Add(com);
                db.SaveChanges();

            }
            return RedirectToAction("Preview", new { id = id });
        }

        public ActionResult Videos()
        {
            return View();
        }

        public ActionResult Projects()
        {
            return View();
        }
    }
}

MainDMMM/Views/Publications/News.cshtml
@model PagedList.IPagedList<MainDMMM.Models.Entities.Post>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" />
@using System.Text.RegularExpressions;
@helper Truncate(string input, int lenght)
{
    if (input.Length <= lenght)
    {
        @Html.Raw(input)
    }
    else
    {
        @Html.Raw(input.Substring(0, input.IndexOf(" ", lenght)).ToString())
    }
}
@section Style {

    <link href="~/Content/client/blog.css" rel="stylesheet" />
}
    <div class="" style="background-color:#3c8dbc;padding:10px;color:#ffffff;">
        <h3 style="text-align:center;">News / Updates</h3>
    </div>

<div class="container">


    <div class="row" style="margin-top:50px;">
        <div class="col-md-7">
            @using (Html.BeginForm())
            {

                <div class="input-group" style="margin-left:10px;">
                    <div class="input-group-btn">
                        <button type="submit" class="btn btn-primary">Search</button>
                    </div>
                    <!-- /btn-group -->
                    <input type="text" name="SearchString" value="@ViewBag.CurrentFilter" class="form-control" placeholder="Search...">
                </div>

            }
           <div class="clearfix"></div>

            <div class="vdo-log">
                <div class="heading">
                    <h2>News</h2>
                </div>
                @foreach (var items in Model)
                {
                    <div class="vdo-list" style="margin-bottom:5px;">
                        <div class="vdo-thumb" style="margin-bottom:5px;">
                            <a>
                                @if (items.ImageModels.FirstOrDefault().ImageContent != null)
                                {

                                    <img src="data:image/jpg;base64,@(Convert.ToBase64String(items.ImageModels.FirstOrDefault().ImageContent))" class="" alt="" />


                                }

                            </a>
                        </div>
                        <div class="vdo-info">
                            <div class="vdo-title">
                                <a href="@Url.Action("Preview", new { id = items.Id })">
                                    <h3>@items.Title</h3>
                                </a>
                            </div>
                            <div class="vdo-desc" style="margin-bottom:5px;">
                                @{

                                    var noHtml = Regex.Replace(items.Content, @"<[^>]*(>|$)|&nbsp;|&zwnj;|&raquo;|&laquo;", string.Empty).Trim();
                                    items.Content = noHtml;
                                }

                                @Html.Raw(Truncate(noHtml, 210))...
                                <br />
                                <div class="vdo-detail">@items.DatePosted.ToString("mm:hh tt") <span>|</span> @items.Comments.Count() <a href="#">Comment</a></div>
                            </div>
                            <div class="clear"></div>
                            <div class="clearfix"></div>
                        </div>


                    </div>

                }
                @*<div>

                    <p>Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount</p>

                    @Html.PagedListPager(Model, page => Url.Action("News",
    new { page }))
                </div>*@
            </div>
        </div>
            <div class="col-md-5">
                <div class="row">
                    <div class="col-md-10">
                        <h3 style="padding-bottom:5px;border-bottom:2px solid #3c8dbc;">Top Events</h3>

                        <div class="panel">
                            @foreach (var item in ViewBag.events)
                            {
                                <div class="panel-body" style="text-align:left;border-bottom:1px solid #3c8dbc;padding:5px 15px;padding-left:0px;">
                                    <h4 style="color:#3c8dbc;">@item.Subject</h4>
                                    <p style="line-height:1.2;">@item.DIscription</p>
                                    <p>@item.Start.ToString("dd-MMMM-yyyy")</p>
                                </div>
                            }

                        </div>
                    </div>
                </div>
              


            </div>

       
        </div>
    </div>

MainDMMM/Views/Publications/Preview.cshtml
@model MainDMMM.Models.Entities.Post

@{
    ViewBag.Title = "Preview";
}

<div class="" style="background-color:#3c8dbc;padding:10px;color:#ffffff;">
    <h3 style="text-align:center;">News / Update</h3>
</div>

<div class="container">


    <div class="row" style="margin-top:50px;">
        <div class="col-md-7">
            <div class="content">
                <div class="vdo-log margin_bottom">
                    <div class="heading6">
                        <h1>@Model.Title</h1>
                    </div>
                    <br />
                    <div class="video-player"><img src="data:image/jpg;base64,@(Convert.ToBase64String(ViewBag.firstimage))" class="img-responsive" alt="" style="margin:0 auto;" /></div>
                    <br /><div class="">

    <div class="vb-desc"><a href="#" rel="nofollow">@Model.DatePosted</a> <span>|</span> <a href="#" rel="nofollow">Comment (@Model.Comments.Count())</a> <span>|</span> </div>

    <div class="clear"></div>
    <div class="">
        <p class="text-justify">
            @Html.Raw(Model.Content)
        </p>
    </div>
    <hr style="border:1px solid #3c8dbc;" />
    <div style="margin:15px 0;">
        @if (Model.Comments == null)
        {
            <h4>No Comment</h4>
        }
        else
        {
           foreach (var i in Model.Comments)
            {
                <span style="color:#3c8dbc;font-weight:bold;font-size:12px;">@i.Name |</span>
                <span style="color:#3c8dbc;font-weight:bold;font-size:12px;">@i.Email |</span>
                <span style="color:#3c8dbc;font-weight:bold;font-size:12px;">@i.DateCommented</span>
                <br />
                <p>@i.Content</p>

            }
        }

    </div>
    <hr style="border:1px solid #3c8dbc;" />
    <div class="">
        @using (Html.BeginForm("Comment", "Publications", new { id = @Model.Id }, FormMethod.Post, null))
        {
            @Html.AntiForgeryToken()
            <div class="row">
                <div class="col-sm-6"><input type="text" name="name" placeholder="Fullname" class="form-control"></div>
                <div class="col-sm-6"><input type="text" name="Email" placeholder="Email" class="form-control"></div>
            </div>
            <br />
            <div class="row">
                <div class="col-sm-12">
                    <label>Comment</label><br />
                    <textarea name="text" rows="4" class="form-control">

</textarea>

                </div>
            </div>
            <br />
            <div class="col-sm-12">
                <button type="submit" class="btn btn-primary btn-flat">Comment</button>
            </div>

        }
    </div>
</div>
                </div>
            </div>
        </div>
        <div class="col-md-5">
            <div class="row">
                <div class="col-md-10">
                    <h3 style="padding-bottom:5px;border-bottom:2px solid #3c8dbc;">Top Events</h3>

                    <div class="panel">
                        @foreach (var item in ViewBag.events)
                        {
                            <div class="panel-body" style="text-align:left;border-bottom:1px solid #3c8dbc;padding:5px 15px;padding-left:0px;">
                                <h4 style="color:#3c8dbc;">@item.Subject</h4>
                                <p style="line-height:1.2;">@item.DIscription</p>
                                <p>@item.Start.ToString("dd-MMMM-yyyy")</p>
                            </div>
                        }

                    </div>
                </div>
            </div>



        </div>


    </div>
</div>
<br /><br />

MainDMMM/Views/Publications/Projects.cshtml
@{
    ViewBag.Title = "Projects";
}


<div class="" style="background-color:#3c8dbc;padding:10px;color:#ffffff;">
    <h3 style="text-align:center;">Projects</h3>
</div>
<div class="container-fluid">

    <div class="row">
        <div class="col-md-12">

            <div class="">

                <div class="row">

                    <div class="col-md-12" style="margin-top:30px;margin-bottom:50px;">
                        <div class="panel" style="box-shadow:1px 1px 1px #3c8dbc;border:1px solid #3c8dbc;">
                            <div class="panel-body text-center">
                                <p>
                                    Content Coming Soon...
                                </p>

                            </div>
                        </div>
                    </div>

                </div>



            </div>
        </div>
    </div>
</div>

MainDMMM/Views/Publications/Videos.cshtml
@{
    ViewBag.Title = "Videos";
}


<div class="" style="background-color:#3c8dbc;padding:10px;color:#ffffff;">
    <h3 style="text-align:center;">Videos</h3>
</div>
<div class="container-fluid">

    <div class="row">
        <div class="col-md-12">

          
            <div class="">

                <div class="row">

                    <div class="col-md-12" style="margin-top:30px;margin-bottom:50px;">
                        <div class="panel" style="box-shadow:1px 1px 1px #3c8dbc;border:1px solid #3c8dbc;">
                            <div class="panel-body text-center">
                                <p>
                                    Content Coming Soon...
                                </p>

                            </div>
                        </div>
                    </div>

                </div>



            </div>
        </div>
    </div>
</div>