MainDMMM/Models/Entities/HallOfFame.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MainDMMM.Models.Entities
{
    public class HallOfFame
    {
        public int Id { get; set; }
        public string Name { get; set; }
        [Display(Name = "Sort Order")]
        public int SortOrder { get; set; }
        public byte[] Image { get; set; }
        [AllowHtml]
        public string Content { get; set; }
        [Display(Name = "Date Created")]
        public DateTime DateCreated { get; set; }
    }
}

MainDMMM/Areas/AdminPanel/Controllers/HallOfFamesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MainDMMM.Models;
using MainDMMM.Models.Entities;
using MainDMMM.Areas.Data.IServices;
using MainDMMM.Areas.Data.Services;

namespace MainDMMM.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin,SuperAdmin")]
    public class HallOfFamesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private IHallOfFameService _hallOfFameService = new HallOfFameService();


        public HallOfFamesController()
        {

        }
        public HallOfFamesController(HallOfFameService hallOfFameService)
        {
            _hallOfFameService = hallOfFameService;
        }
        // GET: Admin/HallOfFames
        public async Task<ActionResult> Index()
        {
            var items = await _hallOfFameService.List();
            return View(items);
        }

        // GET: Admin/HallOfFames/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var hallOfFame = await _hallOfFameService.Get(id);
            if (hallOfFame == null)
            {
                return HttpNotFound();
            }
            return View(hallOfFame);
        }

        // GET: Admin/HallOfFames/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/HallOfFames/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(HallOfFame hallOfFame, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                await _hallOfFameService.Create(hallOfFame, upload);
               
                return RedirectToAction("Index");
            }

            return View(hallOfFame);
        }

        // GET: Admin/HallOfFames/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var hallOfFame = await _hallOfFameService.Get(id);
            if (hallOfFame == null)
            {
                return HttpNotFound();
            }
            return View(hallOfFame);
        }

        // POST: Admin/HallOfFames/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(HallOfFame hallOfFame, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                await _hallOfFameService.Edit(hallOfFame, upload);
                return RedirectToAction("Index");
            }
            return View(hallOfFame);
        }

        // GET: Admin/HallOfFames/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var hallOfFame = await _hallOfFameService.Get(id);
            if (hallOfFame == null)
            {
                return HttpNotFound();
            }
            return View(hallOfFame);
        }

        // POST: Admin/HallOfFames/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            await _hallOfFameService.Delete(id);
            
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MainDMMM/Areas/AdminPanel/Views/HallOfFames/Create.cshtml
@model MainDMMM.Models.Entities.HallOfFame

@{
    ViewBag.Title = "Create";
}
<div class="row">
    <!-- left column -->
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">New Hall Of Fame</h3>
                @if (TempData["error"] != null)
                {
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        <h4><i class="icon fa fa-ban"></i> Alert!</h4>
                        @TempData["error"]
                    </div>
                }
            </div>
            @using (Html.BeginForm("Create", "HallOfFames", null, FormMethod.Post, new { id = "", enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="box-body">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group">
                        @Html.Label("Name", htmlAttributes: new { @class = "control-label" })
                        <div class="">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>



                    <div class="form-group">
                        @Html.Label("Sort Order", htmlAttributes: new { @class = "control-label" })
                        <div class="">
                            @Html.EditorFor(model => model.SortOrder, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.SortOrder, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Content", htmlAttributes: new { @class = "control-label" })
                        <div class="">
                            <textarea class="textarea" placeholder="Place some text here" name="Content" id="mytextarea"
                                      style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"></textarea>
                            @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Image", htmlAttributes: new { @class = "control-label" })
                        <div class="">
                            <input type="file" name="upload" multiple="multiple" class="form-control" required="required" />

                        </div>
                    </div>


                </div>

                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a href="javascript: history.back()" class="btn btn-default">Cancel</a>
                </div>

            }
        </div>

    </div>
    <div class="col-md-3"></div>

</div>


@section Style {

    <link rel="stylesheet" href="~/Content/Admin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">
}

@section Scripts {
    <!-- DataTables -->
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Content/Admin/bower_components/ckeditor/ckeditor.js"></script>
    <!-- Bootstrap WYSIHTML5 -->
    <script src="~/Content/Admin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>

}

@section Scripts2 {
    <script src="~/Content/Admin/tinymce/js/tinymce/tinymce.min.js"></script>
    @*<script src='https://cloud.tinymce.com/stable/tinymce.min.js'></script>*@
    <script>
        tinymce.init({
            selector: '#mytextarea'
        });
    </script>
    @*<script>
            $(function () {
                // Replace the <textarea id="editor1"> with a CKEditor
                // instance, using default configuration.
                CKEDITOR.replace('editor1')
                //bootstrap WYSIHTML5 - text editor
                $('.textarea').wysihtml5()
            })
        </script>*@
}

MainDMMM/Areas/AdminPanel/Views/HallOfFames/Delete.cshtml
@model MainDMMM.Models.Entities.HallOfFame

@{
    ViewBag.Title = "Delete";
}

<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <div class="box box-default">
            <div class="box-header with-border">
                <i class="fa fa-warning"></i>

                <h3 class="box-title">Delete Hall Of Fame</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <div class="alert alert-danger alert-dismissible">

                    <h4>
                        <i class="icon fa fa-ban"></i> Alert! Are you sure you want to delete this?
                    </h4>
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Name)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Name)
                        </dd>

                    </dl>
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-actions no-color btn-delete">
                            <input type="submit" value="Delete" class="btn btn-default" /> &nbsp;
                            <a href="javascript: history.back()" class="btn btn-default">Cancel</a>

                        </div>
                    }


                </div>

            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->


    <div class="col-md-3"></div>

</div>

MainDMMM/Areas/AdminPanel/Views/HallOfFames/Details.cshtml
@model MainDMMM.Models.Entities.HallOfFame

@{
    ViewBag.Title = "Details";
}


<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <div class="box box-default">
            <div class="box-header with-border">
               
                <h3 class="box-title">Details of Hall Of Fame</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Name)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Name)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.SortOrder)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.SortOrder)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Image)
                    </dt>

                    <dd>
                        <img src="data:image/jpg;base64,@(Convert.ToBase64String(Model.Image))" class="img-responsive" style="margin-left:auto;margin-right:auto;max-height:300px;">

                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Content)
                    </dt>

                    <dd>
                        @Html.Raw(Model.Content)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.DateCreated)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.DateCreated)
                    </dd>

                </dl>

            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->


    <div class="col-md-3"></div>

</div>

MainDMMM/Areas/AdminPanel/Views/HallOfFames/Edit.cshtml
@model MainDMMM.Models.Entities.HallOfFame

@{
    ViewBag.Title = "Edit";
}



<div class="row">
    <!-- left column -->
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Edit Hall Of Fame</h3>
                @if (TempData["error"] != null)
                {
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        <h4><i class="icon fa fa-ban"></i> Alert!</h4>
                        @TempData["error"]
                    </div>
                }
            </div>
            @using (Html.BeginForm("Edit", "HallOfFames", null, FormMethod.Post, new { id = "", enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="box-body">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Id)
                    @Html.HiddenFor(model => model.Image)
                    @Html.HiddenFor(model => model.DateCreated)

                    <div class="form-group">
                        @Html.Label("Name", htmlAttributes: new { @class = "control-label" })
                        <div class="">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <div class="form-group">
                        @Html.Label("Sort Order", htmlAttributes: new { @class = "control-label" })
                        <div class="">
                            @Html.EditorFor(model => model.SortOrder, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.SortOrder, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Previous Image", htmlAttributes: new { @class = "control-label" })
                        <div class="">
                            <img src="data:image/jpg;base64,@(Convert.ToBase64String(Model.Image))" class="img-responsive" style="margin-left:auto;margin-right:auto;">

                        </div>
                    </div>
                    <div class="form-group">
                        @Html.Label("New Image Upload", htmlAttributes: new { @class = "control-label" })
                        <div class="">
                            <input type="file" name="upload" multiple="multiple" class="form-control" />

                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Content", htmlAttributes: new { @class = "control-label" })
                        <div class="">
                            <textarea class="textarea" placeholder="Place some text here" name="Content" id="mytextarea"
                                      style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;">@Html.Raw(Model.Content)</textarea>

                            @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
                        </div>
                    </div>


                </div>
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a href="javascript: history.back()" class="btn btn-default">Cancel</a>
                </div>

            }
        </div>

    </div>
    <div class="col-md-3"></div>

</div>

@section Style {

    <link rel="stylesheet" href="~/Content/Admin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">
}

@section Scripts {
    <!-- DataTables -->
    <script src="~/Content/Admin/bower_components/ckeditor/ckeditor.js"></script>
    <!-- Bootstrap WYSIHTML5 -->
    <script src="~/Content/Admin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>

}

@section Scripts2 {

    <script src="~/Content/Admin/tinymce/js/tinymce/tinymce.min.js"></script>
    @*<script src='https://cloud.tinymce.com/stable/tinymce.min.js'></script>*@
    <script>
        tinymce.init({
            selector: '#mytextarea'
        });
    </script>
    @*<script>
            $(function () {
                // Replace the <textarea id="editor1"> with a CKEditor
                // instance, using default configuration.
                CKEDITOR.replace('editor1')
                //bootstrap WYSIHTML5 - text editor
                $('.textarea').wysihtml5()
            })
        </script>*@
}

MainDMMM/Areas/AdminPanel/Views/HallOfFames/Index.cshtml
@model IEnumerable<MainDMMM.Models.Entities.HallOfFame>

@{
    ViewBag.Title = "Index";
}


<div class="row">
    <div class="col-xs-12">
        <div class="box" style="padding:7px;">
            <div class="box-header" style="margin-bottom:15px;">
                <h3 class="box-title"><i class="fa fa-fw fa-file-text-o"></i> Hall Of Fame Management</h3>

                <div class="box-tools">
                    @Html.ActionLink("New Fame", "Create", null, new { @class = "btn btn-primary", style = "padding: 7px;" })
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
                <table id="example1" class="table table-bordered table-hover">

                    <thead>
                        <tr>
                            <th>S/N</th>
                            <th>
                                Image
                            </th>
                            <th>
                                Name
                            </th>
                            <th>
                                Date
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            int sno = 0;
                        }
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @{ sno++; }
                                    @sno
                                </td>
                                <td>
                                    <img src="data:image/jpg;base64,@(Convert.ToBase64String(item.Image))" class="img-responsive" style="margin-left:auto;margin-right:auto;max-height:150px;max-width:150px;">
                                </td>
                                <td>
                                    @item.Name
                                </td>
                                <td>
                                    @item.DateCreated
                                </td>
                                <td>

                                    <div class="dropdown">
                                        <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                                            Action
                                            <span class="caret"></span>
                                        </button>
                                        <ul class="dropdown-menu">

                                            <li class="text-color-warning">@Html.ActionLink("Edit", "Edit", new { id = item.Id }, null)</li>
                                            <li class="text-color-success">@Html.ActionLink("Details", "Details", new { id = item.Id }, null)</li>

                                            <li class="text-color-danger">@Html.ActionLink("Delete", "Delete", new { id = item.Id }, null)</li>

                                        </ul>
                                    </div>

                                </td>
                            </tr>
                        }
                        </tbody>
                </table>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>


    @section Style {

        <link rel="stylesheet" href="~/Content/Admin/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">

    }

    @section Scripts {
        <!-- DataTables -->
        <script src="~/Content/Admin/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
        <script src="~/Content/Admin/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

    }

    @section Scripts2 {
        <script>
        $(function () {
            $('#example1').DataTable()
            $('#example2').DataTable({
                'paging': true,
                'lengthChange': false,
                'searching': false,
                'ordering': true,
                'info': true,
                'autoWidth': false
            })
        })
        </script>
    }

</div>