MainDMMM/Models/Entities/Section.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MainDMMM.Models.Entities
{
    public class Section
    {
        public int Id { get; set; }
        public string Name { get; set; }
        [Display(Name = "Date Created")]
        public DateTime DateCreated { get; set; }
        [Display(Name = "Sub Sections")]
        public ICollection<Subsection> Subsections { get; set; }
    }
}

MainDMMM/Areas/AdminPanel/Controllers/SectionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MainDMMM.Models;
using MainDMMM.Models.Entities;
using MainDMMM.Areas.DataService.IServices;
using MainDMMM.Areas.DataService.Services;

namespace MainDMMM.Areas.AdminPanel.Controllers
{
    [Authorize]
    public class SectionsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ISectionService _sectionService = new SectionService();


        public SectionsController()
        {

        }
        public SectionsController(SectionService sectionService)
        {
            _sectionService = sectionService;
        }
        // GET: AdminPanel/Sections
        public async Task<ActionResult> Index()
        {
            var items = await _sectionService.List();
            return View(items);
        }

        public async Task<ActionResult> Subsectionbysection(int id)
        {
            var items = await _sectionService.ListSubSectionBySectionId(id);
            var sectionName = await _sectionService.Get(id);
            ViewBag.sectionName = sectionName.Name;
            return View(items);
        }

        // GET: AdminPanel/Sections/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Section section = await db.Sections.FindAsync(id);
            if (section == null)
            {
                return HttpNotFound();
            }
            return View(section);
        }

        // GET: AdminPanel/Sections/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AdminPanel/Sections/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Section section)
        {
            if (ModelState.IsValid)
            {
                await _sectionService.Create(section);
                return RedirectToAction("Index");
            }

            return View(section);
        }

        // GET: AdminPanel/Sections/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var section = await _sectionService.Get(id);
            if (section == null)
            {
                return HttpNotFound();
            }
            return View(section);
        }

        // POST: AdminPanel/Sections/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Section section)
        {
            if (ModelState.IsValid)
            {
                await _sectionService.Edit(section);
                return RedirectToAction("Index");
            }
            return View(section);
        }

        // GET: AdminPanel/Sections/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var section = await _sectionService.Get(id);
            if (section == null)
            {
                return HttpNotFound();
            }
            return View(section);
        }

        // POST: AdminPanel/Sections/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            await _sectionService.Delete(id);
            return RedirectToAction("Index");
        }

        #region /*Subsection region*/

        // GET: AdminPanel/Sections
        public async Task<ActionResult> SubsectionIndex()
        {
            var items = await _sectionService.ListSubSection();
            return View(items);
        }

        // GET: AdminPanel/Sections/Details/5
        public async Task<ActionResult> SubsectionDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var section = await _sectionService.GetSubSection(id);
            if (section == null)
            {
                return HttpNotFound();
            }
            return View(section);
        }

        // GET: AdminPanel/Sections/Create
        public ActionResult SubsectionCreate()
        {
            ViewBag.SectionId = new SelectList(db.Sections, "Id", "Name");
            return View();
        }

        // POST: AdminPanel/Sections/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SubsectionCreate(Subsection items, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                await _sectionService.CreateSubSection(items, upload);
                return RedirectToAction("Index");
            }
            ViewBag.SectionId = new SelectList(db.Sections, "Id", "Name", items.SectionId);
            return View(items);
        }

        // GET: AdminPanel/Sections/Edit/5
        public async Task<ActionResult> SubsectionEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var item = await _sectionService.GetSubSection(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            ViewBag.SectionId = new SelectList(db.Sections, "Id", "Name", item.SectionId);
            return View(item);
        }

        // POST: AdminPanel/Sections/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SubsectionEdit(Subsection item, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                await _sectionService.EditSubSection(item, upload);
                return RedirectToAction("Index");
            }
            ViewBag.SectionId = new SelectList(db.Sections, "Id", "Name", item.SectionId);
            return View(item);
        }

        // GET: AdminPanel/Sections/Delete/5
        public async Task<ActionResult> SubsectionDelete(int? id)
        {
            if (id == null)
            {

                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var item = await _sectionService.GetSubSection(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: AdminPanel/Sections/Delete/5
        [HttpPost, ActionName("SubsectionDeleteConfirmed")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SubsectionDeleteConfirmed(int id)
        {
            await _sectionService.DeleteSubSection(id);
            return RedirectToAction("Index");
        }
        #endregion
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MainDMMM/Areas/AdminPanel/Views/Sections/Create.cshtml
@model MainDMMM.Models.Entities.Section

@{
    ViewBag.Title = "Create";
}

<div class="row">
    <!-- left column -->
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">New Apostolate</h3>
              
            </div>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="box-body">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group">
                        @Html.Label("Name", htmlAttributes: new { @class = "control-label" })
                        <div class="">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>


                </div>

                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a href="javascript: history.back()" class="btn btn-default">Cancel</a>
                </div>

            }
        </div>

    </div>
    <div class="col-md-3"></div>

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MainDMMM/Areas/AdminPanel/Views/Sections/Delete.cshtml
@model MainDMMM.Models.Entities.Section

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Section</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MainDMMM/Areas/AdminPanel/Views/Sections/Details.cshtml
@model MainDMMM.Models.Entities.Section

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Section</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MainDMMM/Areas/AdminPanel/Views/Sections/Edit.cshtml
@model MainDMMM.Models.Entities.Section

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Section</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateCreated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateCreated, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateCreated, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MainDMMM/Areas/AdminPanel/Views/Sections/Index.cshtml
@model IEnumerable<MainDMMM.Models.Entities.Section>

@{
    ViewBag.Title = "Index";
}


<div class="row">
    <div class="col-xs-12">
        <div class="box" style="padding:7px;">
            <div class="box-header" style="margin-bottom:15px;">
                <h3 class="box-title"><i class="fa fa-fw fa-file-text-o"></i> Apostolate Management</h3>

            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
                <table id="example1" class="table table-bordered table-hover" border="1">

                    <thead>
                        <tr>
                            <th>S/N</th>
                            <th>
                                Apostolate Section
                            </th>
                            <th>
                                Total
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            int sno = 0;
                        }
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @{ sno++; }
                                    @sno
                                </td>
                                <td>
                                    @item.Name
                                </td>
                                <td>
                                    @item.Subsections.Count()
                                </td>
                                <td>

                                    <div class="dropdown">
                                        <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                                            Action
                                            <span class="caret"></span>
                                        </button>
                                        <ul class="dropdown-menu">

                                            <li class="text-color-success">@Html.ActionLink("Details", "Subsectionbysection", new { id = item.Id }, null)</li>

                                        </ul>
                                    </div>

                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
</div>




@section Style {

    <link rel="stylesheet" href="~/Content/Admin/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
}

@section Scripts {
    <!-- DataTables -->
    <script src="~/Content/Admin/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="~/Content/Admin/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

    <script>
        $(function () {
            $('#example1').DataTable()
            $('#example2').DataTable({
                'paging': true,
                'lengthChange': false,
                'searching': false,
                'ordering': true,
                'info': true,
                'autoWidth': false
            })
        })
    </script>
}

MainDMMM/Areas/AdminPanel/Views/Sections/SubsectionCreate.cshtml
@model MainDMMM.Models.Entities.Subsection

@{
    ViewBag.Title = "SubsectionCreate";
}

<div class="row">
    <!-- left column -->
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">New</h3>

            </div>
            @using (Html.BeginForm("SubsectionCreate", "Sections", null, FormMethod.Post, new { id = "", enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

            <div class="box-body">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.Label("Name", htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.NameOfSection, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.NameOfSection, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.WebsiteUrl, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.WebsiteUrl, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.WebsiteUrl, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CheckResultUrl, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.CheckResultUrl, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CheckResultUrl, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SectionId, "SectionId", htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @Html.DropDownList("SectionId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.SectionId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SchoolLogo, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        <input type="file" name="upload" class="form-control" />
                    </div>
                </div>

                </div>

                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a href="javascript: history.back()" class="btn btn-default">Cancel</a>
                </div>

            }
        </div>

    </div>
    <div class="col-md-3"></div>

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MainDMMM/Areas/AdminPanel/Views/Sections/SubsectionDelete.cshtml
@model MainDMMM.Models.Entities.Subsection

@{
    ViewBag.Title = "SubsectionDelete";
}


<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <div class="box box-default">
            <div class="box-header with-border">
                <i class="fa fa-warning"></i>

                <h3 class="box-title">Delete</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <div class="alert alert-danger alert-dismissible">

                    <h4>
                        <i class="icon fa fa-ban"></i> Alert! Are you sure you want to delete this?
                    </h4>
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.NameOfSection)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.NameOfSection)
                        </dd>

                    </dl>
                    @using (Html.BeginForm("SubsectionDelete", "Sections", new { id = Model.Id }, FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-actions no-color btn-delete">
                            <input type="submit" value="Delete" class="btn btn-default" /> &nbsp;
                            <a href="javascript: history.back()" class="btn btn-default">Cancel</a>

                        </div>
                    }


                </div>

            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->


    <div class="col-md-3"></div>

</div>

MainDMMM/Areas/AdminPanel/Views/Sections/SubsectionDetails.cshtml
@model MainDMMM.Models.Entities.Subsection

@{
    ViewBag.Title = "SubsectionDetails";
}


<div class="row">
    <!-- left column -->
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Edit</h3>

            </div>

            <div class="box-body">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Section.Name)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Section.Name)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.NameOfSection)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.NameOfSection)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.WebsiteUrl)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.WebsiteUrl)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.CheckResultUrl)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.CheckResultUrl)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.DateCreated)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.DateCreated)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.SchoolLogo)
                    </dt>

                    <dd>
                        @if (Model.SchoolLogo != null)
                        {
                            <img src="data:image/jpg;base64,@(Convert.ToBase64String(Model.SchoolLogo))" class="img-responsive" style="width:150px;" />

                        }
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Address)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Address)
                    </dd>

                </dl>
            </div>
            <p>
                @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
                @Html.ActionLink("Back to List", "Index")
            </p>


        </div>
        <div class="col-md-3"></div>
</div>
</div>

MainDMMM/Areas/AdminPanel/Views/Sections/SubsectionEdit.cshtml
@model MainDMMM.Models.Entities.Subsection

@{
    ViewBag.Title = "SubsectionEdit";
}


<div class="row">
    <!-- left column -->
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Edit</h3>

            </div>
            @using (Html.BeginForm("SubsectionEdit", "Sections", null, FormMethod.Post, new { id = "", enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

            <div class="box-body">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)
                @Html.HiddenFor(model => model.DateCreated)
                @Html.HiddenFor(model => model.SchoolLogo)


                <div class="form-group">
                    @Html.LabelFor(model => model.NameOfSection, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.NameOfSection, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.NameOfSection, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.WebsiteUrl, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.WebsiteUrl, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.WebsiteUrl, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CheckResultUrl, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.CheckResultUrl, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CheckResultUrl, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SectionId, "SectionId", htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @Html.DropDownList("SectionId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.SectionId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SectionId, "SectionId", htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @if (Model.SchoolLogo != null)
                        {
                            <img src="data:image/jpg;base64,@(Convert.ToBase64String(Model.SchoolLogo))" class="img-responsive" style="width:150px;" />

                        }
                    </div>
                </div>


                <div class="form-group">
                    @Html.LabelFor(model => model.SchoolLogo, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        <input type="file" name="upload" class="form-control" />
                    </div>
                </div>

            </div>

                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a href="javascript: history.back()" class="btn btn-default">Cancel</a>
                </div>

            }
        </div>

    </div>
    <div class="col-md-3"></div>

</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MainDMMM/Areas/AdminPanel/Views/Sections/SubsectionIndex.cshtml
@model IEnumerable<MainDMMM.Models.Entities.Subsection>

@{
    ViewBag.Title = "SubsectionIndex";
}

<h2>SubsectionIndex</h2>

<p>
    @Html.ActionLink("Create New", "SubsectionCreate")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Section.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NameOfSection)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WebsiteUrl)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CheckResultUrl)
        </th> 
        <th>
            img
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Section.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NameOfSection)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.WebsiteUrl)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CheckResultUrl)
        </td>
        <td>
            @if (item.SchoolLogo != null)
            {
                <img src="data:image/jpg;base64,@(Convert.ToBase64String(item.SchoolLogo))" class="img-responsive" style="width:150px;" />

            }
        </td>
        <td>
            @Html.ActionLink("Edit", "SubsectionEdit", new { id=item.Id }) |
            @Html.ActionLink("Details", "SubsectionDetails", new { id=item.Id }) |
            @Html.ActionLink("Delete", "SubsectionDelete", new { id=item.Id })
        </td>
    </tr>
}

</table>